/**
 * Copies pinned third-party libraries out of node_modules into vendor/.
 *
 * vendor/ is committed to the repo so the extension can be built and shipped
 * with zero runtime network access (01-requirements.md §4: "Vendor all
 * third-party libraries", "No CDN references anywhere").
 *
 * Two extra files are generated here rather than copied:
 *
 *  - vendor/babel-runtime/typeof.js — jspdf.es.min.js has a single bare import
 *    of "@babel/runtime/helpers/typeof". Vendoring the helper (and aliasing the
 *    specifier in vite.config.ts) keeps the dependency graph inside vendor/.
 *
 *  - vendor/stubs/unavailable-module.js — jsPDF lazily `import()`s canvg,
 *    dompurify and html2canvas from inside its `.html()` API, which this
 *    extension never calls. Aliasing those specifiers to a throwing stub keeps
 *    them out of the bundle and makes it impossible for that code path to pull
 *    anything in at runtime.
 */
import { copyFileSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const pkg = JSON.parse(readFileSync(join(root, 'package.json'), 'utf8'));
// jspdf and html2canvas are real dependencies: they are the only third-party
// code that ships inside the extension, which is what makes `npm audit
// --omit=dev` a meaningful gate on the published package.
const deps = pkg.dependencies ?? {};

/** @type {{name: string, from: string, to: string}[]} */
const LIBS = [
  { name: 'jspdf', from: 'node_modules/jspdf/dist/jspdf.es.min.js', to: 'vendor/jspdf/jspdf.es.min.js' },
  { name: 'html2canvas', from: 'node_modules/html2canvas/dist/html2canvas.esm.js', to: 'vendor/html2canvas/html2canvas.esm.js' },
];

const write = (relPath, contents) => {
  const dest = join(root, relPath);
  mkdirSync(dirname(dest), { recursive: true });
  writeFileSync(dest, contents);
};

const libs = {};
for (const lib of LIBS) {
  const version = deps[lib.name];
  if (!/^\d+\.\d+\.\d+$/.test(version)) {
    throw new Error(`${lib.name} must be pinned to an exact version, got "${version}"`);
  }
  const dest = join(root, lib.to);
  mkdirSync(dirname(dest), { recursive: true });
  copyFileSync(join(root, lib.from), dest);
  libs[lib.name] = { version, file: lib.to };
  console.log(`vendored ${lib.name}@${version} -> ${lib.to}`);
}

const babelHelper = 'vendor/babel-runtime/typeof.js';
mkdirSync(join(root, dirname(babelHelper)), { recursive: true });
copyFileSync(join(root, 'node_modules/@babel/runtime/helpers/esm/typeof.js'), join(root, babelHelper));
libs['@babel/runtime/helpers/typeof'] = { version: 'ships inside jspdf', file: babelHelper };
console.log(`vendored @babel/runtime/helpers/typeof -> ${babelHelper}`);

write(
  'vendor/stubs/unavailable-module.js',
  `// Generated by scripts/vendor.mjs. Do not edit by hand.
// Stands in for optional jsPDF dependencies (canvg, dompurify, html2canvas)
// that this extension never uses. Reaching this code is a bug, not a network
// fetch: nothing here can load remote code.
const unavailable = () => {
  throw new Error('exporter: this jsPDF feature is not bundled and is not used by this extension');
};
export default new Proxy({}, { get: unavailable, apply: unavailable, construct: unavailable });
`,
);
console.log('generated vendor/stubs/unavailable-module.js');

write(
  'vendor/VENDOR.json',
  `${JSON.stringify({ note: 'Generated by scripts/vendor.mjs. Do not edit by hand.', libs }, null, 2)}\n`,
);
